### ISSUE TITLE
local function cannot be decompile

### ISSUE THREAD

**Issue by weibobo** [jjdredd/ljd#2]
I used luajit 2.0.1 to compile a simple local function lua, but cannot decompile it, the lua file is:
 local function foo(a)  
end
foo("xx")

could u help me on how to solve the problem?

The following is the exception:
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    retval = main()
  File "main.py", line 115, in main
    ljd.ast.validator.validate(ast, warped=False)
  File "E:\tools\ljd2\ljd\ast\validator.py", line 340, in validate
    traverse.traverse(visitor, ast)
  File "E:\tools\ljd2\ljd\ast\traverse.py", line 251, in traverse
    visitor._visit(node)
  File "E:\tools\ljd2\ljd\ast\validator.py", line 332, in _visit
    traverse.Visitor._visit(self, node)
  File "E:\tools\ljd2\ljd\ast\traverse.py", line 238, in _visit
    node._accept(self)
  File "E:\tools\ljd2\ljd\ast\nodes.py", line 22, in _accept
    visitor._visit(self.statements)
  File "E:\tools\ljd2\ljd\ast\validator.py", line 332, in _visit
    traverse.Visitor._visit(self, node)
  File "E:\tools\ljd2\ljd\ast\traverse.py", line 238, in _visit
    node._accept(self)
  File "E:\tools\ljd2\ljd\ast\nodes.py", line 146, in _accept
    visitor._visit_list(self.contents)
  File "E:\tools\ljd2\ljd\ast\traverse.py", line 244, in _visit_list
    self._visit(node)
  File "E:\tools\ljd2\ljd\ast\validator.py", line 332, in _visit
    traverse.Visitor._visit(self, node)
  File "E:\tools\ljd2\ljd\ast\traverse.py", line 238, in _visit
    node._accept(self)
  File "E:\tools\ljd2\ljd\ast\nodes.py", line 253, in _accept
    visitor._visit(self.function)
  File "E:\tools\ljd2\ljd\ast\validator.py", line 327, in _visit
    restrictions.check(node)
  File "E:\tools\ljd2\ljd\ast\validator.py", line 28, in check
    .format(type(node), typespec)
AssertionError: Invalid node type: <class 'ljd.ast.nodes.FunctionDefinition'> should be: (<class 'ljd.ast.nodes.Identifier'>, <class 'ljd.ast.nodes.TableElement'>, <class 'ljd.ast.nodes.MULTRES'>)

**Comment by jjdredd** [comment]
Hi and thanks. I will try to test further, but the decompiler itself needs a major fix, so this probably is a long term issue.

**Comment by weibobo** [comment]
Thanks, the decompiler is very good under most conditions. I thought it just need a small fix for this problem. I'll take some time to study the code too, it seems complicated on local variables.

**Comment by weibobo** [comment]
Could u tell me the major problems on current version? this can help me find the way to solve it.

**Comment by jjdredd** [comment]
The decompiler works mostly fine for not stripped bytecode. The problems start with stripped bytecode.
As I understand, the most fragile and buggy parts are local var detection and AST unwarper (basic control flow and expression analysis). Unfortunately I haven't had much time myself so I didn't do much to fix the decompiler. It needs a new design imo. Here are some interesting conversations with the original author @NightNord:
https://github.com/NightNord/ljd/issues/14
https://github.com/NightNord/ljd/issues/13

**Comment by weibobo** [comment]
thank you, i'll give it a try.

**Comment by jjdredd** [comment]
ok, the last commit on branch bugfix should fix it for the 'truly' local functions. It breaks the decompiler for 'semi-local' functions like this:

``` lua
local function g(x)
    ....
end
j = g
...

```

**Comment by jjdredd** [comment]
nahh, looks like this 'fix' breaks the decompiler.
