### ISSUE TITLE
 assert len(info.references) == 2 error

### ISSUE THREAD

**Issue by Danewalker** [jjdredd/ljd#4]
ljd exit with following error: 
Traceback (most recent call last):
  File "main.py", line 123, in <module>
    retval = main()
  File "main.py", line 99, in main
    ljd.ast.slotworks.eliminate_temporary(ast)
  File "w:\work\ljd\ast\slotworks.py", line 14, in eliminate_tempo
rary
    _eliminate_temporary(slots)
  File "w:\work\ljd\ast\slotworks.py", line 46, in _eliminate_temp
orary
    _fill_massive_refs(info, simple, massive, iterators)
  File "w:\work\ljd\ast\slotworks.py", line 68, in _fill_massive_r
efs
    assert len(info.references) == 2
AssertionError
## Lua source from pbc lua

local lpeg = require "lpeg"
local P = lpeg.P
local V = lpeg.V

local next = next

local proto_tbl = { "PROTO" }

local k, v = next(patterns)
local p = V(k)
proto_tbl[k] = v    --- Error

return parser

**Comment by jjdredd** [comment]
thanks for reporting, please provide branch name and commit number

**Comment by Danewalker** [comment]
i'm using branch - bugfix with latest commit

**Comment by jjdredd** [comment]
please, try master

**Comment by jjdredd** [comment]
@Danewalker do you get the same on master branch?

**Comment by tboby** [comment]
I have the same issue, and cannot reproduce it on master because of the non-propagation of the stripped flag causing everything to get misaligned. If I cherry-pick Commit 9351dbe6f9cb5912bdc7f7d0059dec37984e9c82 then I get the same error.

I've vaguely tried to follow the AST process in debug to see how it happens, but it's a bit much!

**Comment by jjdredd** [comment]
@ThomasBoby thanks, but that's odd. I don't know why that patch could cause trouble.
If you have interest in source/algo, ask away. I haven't read much of the code but I might be able to help.

**Comment by tboby** [comment]
@jjdredd 
I've managed to find the minimum example where it fails.

```
local k,v = next(patterns)
local q = V(k)
local p = V(k)
```

If you comment out the assert it then suceeds, but it doesn't link the k in local k,v with the k in the later instructions.

This seems to be an issue relating to "massive" boxes and having multiple following references to them. You can't get around it by having an intermediate variable either, as it gets optimized out :)
